language: r
sudo: false
cache: packages

r_check_args: "--as-cran --run-dontrun"

after_success:
- Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: never
    on_failure: never
  slack: huckley:XufS5mf1g1GF3MjqPMVVcyAB
    