language: r
sudo: true
cache: packages


after_success:
- Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: never
    on_failure: never
  slack: huckley:XufS5mf1g1GF3MjqPMVVcyAB
    